### PR TITLE
feat: add base components to start migration to react

### PR DESCRIPTION
**Pull request by SOY4RIAS**

### CODE REVIEW

**Review by dsandoval11 — DISMISSED** [review]

**Comment by SOY4RIAS** [comment]
@mergify update

**Comment by SOY4RIAS** [comment]
@mergify update

**Comment by SOY4RIAS** [comment]
@mergify update

**Comment by SOY4RIAS** [comment]
@mergify queue

**Review by dsandoval11 — APPROVED** [review]

**Pull request merged**
